# permissions for end users to edit users.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: user-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pco-reseller-operator
    app.kubernetes.io/part-of: pco-reseller-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-editor-role
rules:
- apiGroups:
  - pco.plusserver.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pco.plusserver.com
  resources:
  - users/status
  verbs:
  - get
