{{- if .Values.controllerIdentifier }}
apiVersion: v1
kind: Secret
metadata:
  name: pco-reseller-operator-id
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  id: {{ .Values.controllerIdentifier }}
immutable: true
{{- end  }}